// import './algorithms/binarySearch.js'
// import './algorithms/sort/bubbleSort.js'
// import './algorithms/sort/insertionSort.js'
// import './algorithms/sort/quickSort.js'
import './algorithms/sort/mergeSort.js'